multipass: true

plugins:
  - addAttributesToSVGElement: false
  - addClassesToSVGElement: false
  - cleanupAttrs: true
  - cleanupEnableBackground: true
  - cleanupIDs: true
  - cleanupListOfValues: true
  - cleanupNumericValues:
      floatPrecision: 2
  - collapseGroups: true
  - convertColors: true
  - convertPathData: true
  - convertShapeToPath: true
  - convertStyleToAttrs: true
  - convertTransform: true
  - mergePaths: true
  - minifyStyles: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - removeAttrs:
      attrs: 'fill'
  - addAttributesToSVGElement:
      attributes:
        - fill: 'currentColor'
  - removeComments: true
  - removeDesc: true
  - removeDimensions: true
  - removeDoctype: true
  - removeEditorsNSData: true
  - removeElementsByAttr: false
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - removeEmptyText: true
  - removeHiddenElems: true
  - removeMetadata: true
  - removeNonInheritableGroupAttrs: true
  - removeRasterImages: false
  - removeStyleElement: true
  - removeTitle: true
  - removeUnknownsAndDefaults: true
  - removeUnusedNS: false
  - removeUselessDefs: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: false
  - removeXMLNS: false
  - removeXMLProcInst: true
  - sortAttrs: false
  - transformsWithOnePath: true

js2svg:
  pretty: true
  indent: '  '
