<?php

/**
 * @file
 * Contains particle_theme.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function particle_theme_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the particle_theme module.
    case 'help.page.particle_theme':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Particle and Particle theme utilities') . '</p>';
      return $output;

    default:
  }
}
