const fs = require('fs');
const _ = require('lodash');
const yaml = require('js-yaml');

/**
 * Take a design system namespaces object and convert it to relative paths for
 * app. Write results to config yaml.
 *
 * @param {Object} namespaces - Namespace object generated by design system
 * @param {Object} config - app config
 * @param {Object} config.namespaces - app config around namespace conversion
 * @param {Function} config.namespaces.config - Path to config yaml to read/write
 * @param {Function} config.namespaces.atKey - Lodash set string of path in object
 * @param {Function} config.namespaces.transform - Function to convert path
 * @returns {Function} - Return a closure ready to accept callback
 */
module.exports = function namespaceWriter(namespaces, config) {
  // Returns a function
  return done => {
    // Create namespace paths in the correct relative path each app needs
    const relNamespaces = Object.keys(namespaces).reduce((acc, cat) => {
      const validPaths = namespaces[cat].paths.reduce((paths, atomicPath) => {
        // Each app provides its own transform function :)
        const { componentPath, relativePath } = config.namespaces.transform(
          atomicPath
        );

        // Check if the path has been written to dist, see https://github.com/phase2/particle/issues/503
        if (config.namespaces.skipFileExistenceCheck) {
          paths.push(componentPath);
        } else if (fs.existsSync(relativePath)) {
          paths.push(componentPath);
        }
        return paths;
      }, []);
      if (validPaths.length > 0) {
        acc[cat] = {
          paths: validPaths,
        };
      }
      return acc;
    }, {});

    // Read and then write app config
    fs.readFile(config.namespaces.config, 'utf8', (readErr, data) => {
      if (readErr) {
        console.error(readErr);
        return done();
      }
      // Now load contents
      const appConfig = yaml.safeLoad(data);
      // Use lodash and key shorthand to set key/values
      _.set(appConfig, config.namespaces.atKey, relNamespaces);
      // Write to fs
      return fs.writeFile(
        config.namespaces.config,
        yaml.safeDump(appConfig, { lineWidth: Infinity }),
        'utf8',
        writeErr => {
          if (writeErr) {
            console.error(writeErr);
            return done();
          }
          return done();
        }
      );
    });
  };
};
