export const SET_FILTER = 'SET_FILTER';
export const REQUEST_CRYPTO = 'REQUEST_CRYPTO';
export const REQUEST_CRYPTO_SUCCESS = 'REQUEST_CRYPTO_SUCCESS';
export const REQUEST_CRYPTO_FAIL = 'REQUEST_CRYPTO_FAIL';
