#!/usr/bin/env bash

# Initialize stack.
fin project start

# Run the common init script within the cli container.
fin exec bin/init.sh "$@"

# Repeat here just to show the site URL when we are done.
fin project start
