# This workflow will run tests using node and then publish a package to NPM and GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

#name: Publish Packages
#
#on:
#  push:
#    branches: [ eleven ]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#      - run: npm ci
#      - run: npm test
#
#  publish-npm:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: git config user.email "NEED AUTHORISED EMAIL"
#      - run: git config user.name ${{ github.actor }}
#      - run: npm run postinstall
#      - run: npm run publish:lerna
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#  publish-gpr:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#          registry-url: https://npm.pkg.github.com/
#      - run: npm ci
#      - run: git config user.email "NEED AUTHORISED EMAIL"
#      - run: git config user.name ${{ github.actor }}
#      - run: npm run postinstall
#      - run: npm run publish:lerna
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
